export * from "./home/home/Homepage";
export * from "./home/subpage/movie-detail/MovieDetail";
export * from "./home/subpage/movie-list/MovieList";
export * from "./home/subpage/favorite-movie-list/FavoriteMovieList"
export * from "./log-in/LogInpage";
export * from "./sign-up/SignUppage";
export * from "./admin/admin-home/Adminpage";
export * from "./admin/subpage/add-movie/AddMoviepage";
export * from "./admin/subpage/movie-list/MovieListpage";